version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_APP_CONTAINER_NAME}
    tty: true
    depends_on:
      - db
    working_dir: /var/www
    volumes:
      - ./:/var/www
    links:
      - db:db

  webserver:
    image: nginx:stable
    container_name: ${DOCKER_NGINX_CONTAINER_NAME}
    restart: always
    ports:
      - ${DOCKER_NGINX_PORTS}
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  db:
    image: postgres:15
    container_name: ${DB_HOST}
    restart: always
    volumes:
      - ovikus_testapp_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DOCKER_DB_PORT_EXPOSE}:${DB_PORT}"

volumes:
  ovikus_testapp_db_data:
